name: Todo Api Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Todo Api
    runs-on: ubuntu-latest
    steps:
      - run: echo "Logging into EC2..."
      - name: "Executing remote SSH into EC2"
        uses: "appleboy/ssh-action@v1"
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH }}
          username: ${{ secrets.USERNAME }}
          script: |
            cd ~/todo-api
            git checkout main
            git pull origin main
            npm install
            pm2 restart todo-api
